//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityframeworkDotnet.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class size
    {
        public int id { get; set; }
        public int food_id { get; set; }
        public string size1 { get; set; }

        [Required(ErrorMessage = "Required")]
        public int price { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
