//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityframeworkWebForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class size
    {
        public int id { get; set; }
        public int food_id { get; set; }
        public string size1 { get; set; }
        public int price { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
